build-image:
	docker build -t kshitijrajgude/primetrade-assignment-frontend-alpine .
push-image:
	docker kshitijrajgude/primetrade-assignment-frontend-alpine
run-docker:
	docker run -p 5173:5173 kshitijrajgude/primetrade-assignment-frontend-alpine

