build-image:
	docker build -t kshitijrajgude/primetrade-assignment-backend-alpine .
push-image:
	docker kshitijrajgude/primetrade-assignment-backend-alpine
run-docker:
	docker run -p 3000:3000 kshitijrajgude/primetrade-assignment-backend-alpine

