build-image:
	docker build -t kshitijrajgude/primetrade-assignment-alpine .
push-image:
	docker kshitijrajgude/primetrade-assignment
run-docker:
	docker run -p 3000:3000 kshitijrajgude/primetrade-assignment-alpine

