apiVersion: apps/v1
kind: Deployment
metadata:
  name: primetrade-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: primetrade-backend
          image: kshitijrajgude/primetrade-assignment-backend-alpine:latest
          envFrom:
            - secretRef:
                name: primetrade-backend-secrets
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10
